#FROM python:3.9-slim
#FROM debian:10
# Install Java JDK
FROM openjdk:slim
COPY --from=python:3.9 / /
#FROM python:3.8.8-buster
# Install OpenJDK-8
ENV DefaultOutput = "DefaultOutput"
ENV project_name="project_name"
ENV version_name="version_name"

COPY hello.py /tmp/
RUN mkdir /work/

COPY ./JMONSEL /work

CMD ["python", "/tmp/hello.py"]

